### ISSUE TITLE
placing launch pad and chemical factory causes crash, and little boy and fat man textures are missing

### ISSUE THREAD

**Issue by Globalfirestorm10** [MartinTheDragon/Nuclear-Tech-Mod-Remake#12] opened 2022-08-12 22:57 UTC
**Describe the bug**
title describes the bugs

**To Reproduce**
1. get a fat man and little boy
2. see error
3. get a chemical plant and a launch pad

**Expected behavior**
crashes and missing textures

**Screenshots**

**Software and mod environment info (please complete the following information):**
 - latest
 - additional guns (mcrayfish), ava, crayfish gun mod, codechickenlib, distanthorizons, framework, jei, memoryleakfix, mo' guns, notenoughcrashes, optifine HD_U-H7, cracker's wither storm, and worldedit
 - Forge version: 1.18.2 40.1.0

**Additional context**
[crash-2022-08-12_18.39.42-client.txt](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/9330185/crash-2022-08-12_18.39.42-client.txt)
[crash-2022-08-12_14.02.37-client.txt](https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/files/9330186/crash-2022-08-12_14.02.37-client.txt)

**Comment by MartinTheDragon** [comment] 2022-08-12 22:58
Hi, this is likely a duplicate of #9

**Closed as completed by MartinTheDragon** 2022-08-12 22:58 UTC
Labels: bug, duplicate

**Comment by Globalfirestorm10** [comment] 2022-08-13 01:40
oh, my apologies
