### ISSUE TITLE
Attempted to load class net...client/Minecraft

### ISSUE THREAD

**Issue by ZifyyCZ** [MartinTheDragon/Nuclear-Tech-Mod-Remake#51] opened 2023-03-04 20:27 UTC
### Issue description

Upon dropping or /giving items, or doing some other silly stuff, we all get kicked for "Attempted to load class net.minecraft.client.Minecraft", and cannot join afterwards.

(I'm 99.99% confident it's not my mod's fault this time, as it is using Minecraft.class only client-side, and upon removing NTM we didn't get kicked anymore)

### Steps to reproduce

1. /give or drop an item
2. Get kicked
3. Have to re-do the world

### Forge version

40.1.86

### Nuclear Tech version

0.0.19

### Other mods

- JEI
- Macaw's Bridges
- Macaw's Fences
- Macaw's Roofs
- Macaw's Windows
- Warfront
- Worldedit

**Comment by ZifyyCZ** [comment] 2023-03-04 20:27
version is 0.0.19.1*

**Comment by MartinTheDragon** [comment] 2023-03-04 20:28
Duplicate of #45

**Closed as not planned by MartinTheDragon** 2023-03-04 20:28 UTC
Labels: bug, duplicate

**Comment by ZifyyCZ** [comment] 2023-03-04 20:29
Ah, I see.
Ty for the very very quick response tho.

**Comment by MartinTheDragon** [comment] 2023-03-04 20:29
Either manually compile a version yourself for the server or wait until tomorrow.
Thanks anyway!

**Comment by ZifyyCZ** [comment] 2023-03-04 20:29
I'll wait. :D
