### ISSUE TITLE
Looking at an RBMK reactor can cause significant FPS drops

### ISSUE THREAD

**Issue by minceraft12** [MartinTheDragon/Nuclear-Tech-Mod-Remake#71] opened 2024-02-06 08:46 UTC
### Issue description

When an RBMK reactor is loaded, it causes severe FPS drops.
Example: 100FPS to 15FPS
Expected behaviour: Slight drop in FPS would be fine, and probably unnoticeable.

### Steps to reproduce

1. Make a large RBMK reactor
2. Look at it

### Forge version

40.2.17

### Nuclear Tech version

0.0.20

### Other mods

Oculus 1.6.4 (performance mod)
Embeddium 0.3.0 (performance mod)
Better Fusion Reactor for Mekanism PLUS (unused as of bug report)
Colored Redstone Lamps 1.2
Create 0.5.1.f (unused as of bug report)
Create Deco 1.3.3
Immersive Portals 1.4.20 (unused as of bug report)
JourneyMap 5.9.7
JEI 10.2.1.1005
Macaw's Furniture 3.2.2
Macaw's Lights and Lamps 1.0.6
Mekanism 10.2.5.465
Mekanism Additions 10.2.5.465
Mekanism Generatiors 10.2.5.465
Mekanism Tools 10.2.5.465
Modern Lights 2.3.0
Orva Alarms and Sirens 3.0
SecurityCraft 1.9.8

### (Crash) Log

N/A

**Comment by MartinTheDragon** [comment] 2024-02-07 13:52
Duplicate of #29

**Closed as not planned by MartinTheDragon** 2024-02-07 13:52 UTC
Labels: bug
